### ISSUE TITLE
UTF8 related protobuff error 

### ISSUE THREAD

**Issue by cazitouni** [gis-ops/docker-valhalla#141]
Hello, 

Using your docker compose I got an UTF8 related error 
![image](https://github.com/gis-ops/docker-valhalla/assets/92778930/f3e60b99-c959-4f28-8b8a-505206e817c4)

Didn't find any solution for now but looks quite similar to this one 
[https://github.com/valhalla/valhalla/issues/3465](https://github.com/valhalla/valhalla/issues/3465)
Which seems strange since it's marked as solved for 2 years now and I'm using the latest container. 

What could be the problem, bad enconding on the container ? 

Thanks in advance for any answers,
Regards, Clément.

**Comment by nilsnolde** [comment]
please no screenshot of text, use copy/paste, it's unreadable as it is.

it's an issue for https://github.com/valhalla/valhalla, best open there. might be that some pbf field was added in the meantime with `string` instead of `bytes`. also please include an example request to the public instance at https://valhalla1.openstreetmap.de.
