### ISSUE TITLE
Out Of Memory Error

### ISSUE THREAD

**Issue by akki401** [gis-ops/docker-valhalla#165]
Hello Team,
I hosted 3 different continent docker containers(Europe, Asia and North-America) in i4i.2xlarge which has 8 vCPU and 64GB memory
.
Out of those one docker container of Europe faced the **OUT OF MEMORY** Error and but docker still running but not stopped
**{"log":"FATAL ERROR: OUT OF MEMORY (src/yqueue.hpp:70)\r\n","stream":"stdout","time":"2024-09-29T11:22:39.968056306Z"}**

I checked the RAM usage and found enough memory
![image](https://github.com/user-attachments/assets/58492208-8109-4ee2-95eb-c61afb68b51b)

I am not sure why the container experienced the out of memory issue.

If the docker container face heavy traffic than usual at particular time may lead to this kind of issue?

**Comment by chrstnbwnkl** [comment]
"Enough memory" for what exactly? 62 gigs can easily be exhausted if you hit the service with, say, a large matrix request that is spread geographically, leading not only to a lot tiles being read into the tile cache, but also a big memory footprint due to a large expansion during path finding. So yes, if you don't protect your service against those kinds of requests, this can lead to it being OOM killed.

**Comment by akki401** [comment]
Thankyou
