### ISSUE TITLE
How to update data?

### ISSUE THREAD

**Issue by toton6868** [gis-ops/docker-valhalla#27]
I have an SIT, UAT and Prod environment. Can you discuss a little bit how can I update my Prod environment without stopping the docker or having no maintenance mode? I have updated the data in the UAT environment. Is there any way to copy any folder or data from UAT to Prod? I know the docker `cp` but I do not know which folder needs to be replaced.

**Comment by nilsnolde** [comment]
Can you describe your setup a little more? What data do you need updated? I guess the graph tiles? 

Best paste your docker-compose.yml and explain a little more what exactly you want to achieve.

**Comment by toton6868** [comment]
Yes, I want to update Graph Tiles. If I start processing the OSM data again then it will take a few minutes and the server will be unavailable. This is why I want to get a downtime less server maintenance mode.

**Comment by nilsnolde** [comment]
Still no docker-compose.yml but if you're anywhere near the default setup then you have mapped a host directory to a container directory right? So, all you do is copy over the `valhalla_tiles.tar` from the builder to the runner host direcctory..

you'll _have to_ restart the docker container though, no way around that. ref: https://github.com/valhalla/valhalla/issues/3117. 
I didn't get to that yet, but when it's finished there will be an endpoint on the http service allowing for an actor reset instead of exiting `valhalla_service`.
