### ISSUE TITLE
CMake error "LUA_INCLUDE_DIR-NOTFOUND"

### ISSUE THREAD

**Issue by danirisdiandita** [gis-ops/docker-valhalla#7]
Hi all.

during building docker

`docker build -t gisops/valhalla . && docker run -dt -v $PWD/custom_files:/custom_files -p 8002:8002 --name valhalla_1 valhalla`

I got errors like these
```
CMake Error in bench/thor/CMakeLists.txt:
  Target "valhalla" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "LUA_INCLUDE_DIR-NOTFOUND"


CMake Error in bench/thor/CMakeLists.txt:
  Target "valhalla" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "LUA_INCLUDE_DIR-NOTFOUND"


CMake Error in bench/thor/CMakeLists.txt:
  Target "valhalla" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "LUA_INCLUDE_DIR-NOTFOUND"
```

complete logs shown here 

https://gist.github.com/danirisdiandita/24d144b55245187f4ed2c65ccb0c2408

thank you

**Comment by nilsnolde** [comment]
Yeah, sorry, that's bound to happen with a detached Docker repository. So, you're building from Valhalla's master and the project has been moving along quite a bit since our last update on the Dockerfile. Specifically on Lua they moved to LuaJIT, also tests are way more elaborate. I'd not expect to build even if you fixed the Lua thing. 

I will put this in the documentation: if you can use our images from Dockerhub and we strongly encourage to use release images, e.g. `docker pull gisops/valhalla:3.0.9`. I'll also get rid of `latest` image, too confusing since we can't keep up with Valhalla's `master`, dozens of people working on it lately.

Unfortunately we're very close to a 3.1.0 release, so we're almost as far away from a previous release as we can :( Once it's there we'll update our Docker repo though!

**Comment by nilsnolde** [comment]
Put a note in https://github.com/gis-ops/docker-valhalla#container-recipes

Thanks for making us more aware of this.
